replicaCount: 1

image:
  repository: redis
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  name: redis
  port: 6379
  targetPort: 6379
deployment: 
  name: redis
container:
  name: redis
  port: 6379
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80